# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [ 70, 70 ], mode: outbound }
        optimised:
            quality: 75